version: 2

sources:
  - name: northwind_etl
    description: Northwind tables
    tables:
      - name: orders
      - name: order_details
      - name: products
      - name: shippers
      - name: suppliers
      - name: customers